// Program settings

#define WINDOW_WIDTH 900
#define WINDOW_HEIGHT 600

#define RENDER_MODE RM_RAY_TRACING
#define RAY_TRACING_TARGET RTT_GPU

#define OPENGL_SHADER shdrTexture

#define OPTIX_PRINT_TIME 0
#define OPTIX_USE_GEOMETRY_VBO 1
#define OPTIX_USE_OUTPUT_VBO 1 // Slower rendering, but faster texture and must run on Master thread

#define EMBREE_PRINT_TIME 0
#define EMBREE_SFLAGS_SCENE RTC_SCENE_DYNAMIC | RTC_SCENE_COHERENT | RTC_SCENE_HIGH_QUALITY
#define EMBREE_AFLAGS_SCENE RTC_INTERSECT8
#define EMBREE_SFLAGS_OBJECT RTC_SCENE_STATIC | RTC_SCENE_COHERENT | RTC_SCENE_HIGH_QUALITY
#define EMBREE_AFLAGS_OBJECT RTC_INTERSECT8

#define HYBRID_THREADED 1
#define HYBRID_PARTITION 0.4